name: "docker build release base image"

on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'name'
        required: true
        default: 
      tag:
        description: 'tag'
        required: true
        default: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME_IOIOX }}
          password: ${{ secrets.DOCKER_PASSWORD_IOIOX }}

      - name: Build and push to docker hub
        uses: docker/build-push-action@v2
        with:
          context: base/${{ github.event.inputs.name }}/${{ github.event.inputs.tag }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME_IOIOX }}/${{ github.event.inputs.name }}:${{ github.event.inputs.tag }}

      - name: Login harbor
        uses: docker/login-action@v1 
        with:
          registry: ${{ secrets.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build and push to harbor
        uses: docker/build-push-action@v2
        with:
          context: base/${{ github.event.inputs.name }}/${{ github.event.inputs.tag }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.HARBOR_REGISTRY }}/${{ secrets.HARBOR_PROJECT_IOIOX }}/${{ github.event.inputs.name }}:${{ github.event.inputs.tag }}
